#!/bin/bash
if [ "$(id -u)" -ne 0 ]; then
	echo '  _____ _             _           _'
	echo ' /  ___| |           | |         | |'
	echo ' \ `--.| |_ __ _ _ __| |     __ _| |__  ___'
	echo '  `--. \ __/ _` | '"'"'__| |    / _` | '"'"'_ \/ __|'
	echo ' /\__/ / || (_| | |  | |___| (_| | |_) \__ \'
	echo ' \____/ \__\__,_|_|  \_____/\__,_|_.__/|___/'
	echo
	echo '************** Star Labs Theme *************'
	echo
	echo 'This script must be run by root' >&2
        exit 1
fi

# Main Menu
clear
echo '  _____ _             _           _'
echo ' /  ___| |           | |         | |'
echo ' \ `--.| |_ __ _ _ __| |     __ _| |__  ___'
echo '  `--. \ __/ _` | '"'"'__| |    / _` | '"'"'_ \/ __|'
echo ' /\__/ / || (_| | |  | |___| (_| | |_) \__ \'
echo ' \____/ \__\__,_|_|  \_____/\__,_|_.__/|___/'
echo
echo '************** Star Labs Theme *************'
echo
echo "What would you like to do?"
select d in "Install" "Update" "Uninstall"
do
	break
	echo $d
done
clear

if [ "$d" == "Install" ]; then
	echo '  _____ _             _           _'
	echo ' /  ___| |           | |         | |'
	echo ' \ `--.| |_ __ _ _ __| |     __ _| |__  ___'
	echo '  `--. \ __/ _` | '"'"'__| |    / _` | '"'"'_ \/ __|'
	echo ' /\__/ / || (_| | |  | |___| (_| | |_) \__ \'
	echo ' \____/ \__\__,_|_|  \_____/\__,_|_.__/|___/'
	echo
	echo '************** Star Labs Theme *************'
	echo
	echo "Installing..."
	echo -ne "Fetching submodules..."
	git submodule init
	git pull --recurse-submodules &>/dev/null
	echo "Done"
	echo -ne "Creating build folder..."
	meson build &>/dev/null
	echo "Done"

	echo -ne "Compiling build folder..."
	ninja -C build &>/dev/null
	echo "Done"

	echo -ne "Installing build folder..."
	sudo ninja -C build install &>/dev/null
	echo "Done"

	echo -ne "Installing GDM theme..."
	sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css /usr/share/gnome-shell/theme/StarLabs/gnome-shell.css 47
	echo "Done"

        echo -ne "Compiling schemas..."
        sudo glib-compile-schemas /usr/share/glib-2.0/schemas
        echo "Done"

        echo -ne "Installing Plymouth theme..."
        sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/StarLabs/StarLabs.plymouth 150 --slave /usr/share/plymouth/themes/default.grub default.plymouth.grub /usr/share/plymouth/themes/StarLabs/StarLabs.grub
        sudo update-initramfs -u
        echo "Done"

        echo -ne "Updating grub..."
        sudo update-grub
        echo "Done"

	echo "Installation complete"

elif [ "$d" == "Update" ]; then
        echo '  _____ _             _           _'
        echo ' /  ___| |           | |         | |'
        echo ' \ `--.| |_ __ _ _ __| |     __ _| |__  ___'
        echo '  `--. \ __/ _` | '"'"'__| |    / _` | '"'"'_ \/ __|'
        echo ' /\__/ / || (_| | |  | |___| (_| | |_) \__ \'
        echo ' \____/ \__\__,_|_|  \_____/\__,_|_.__/|___/'
        echo
        echo '************** Star Labs Theme *************'
        echo
        echo "Updating..."
	echo -ne "Uninstalling current version..."
	sudo ninja -C build uninstall &>/dev/null
	echo "Done"
        echo -ne "Fetching submodules..."
	git pull
	git pull --recurse-submodules &>/dev/null

	echo -ne "Reconfiguring build folder..."
        ninja -C build reconfigure &>/dev/null
	echo "Done"

        echo -ne "Compiling build folder..."
        ninja -C build &>/dev/null
	echo "Done"

        echo -ne "Installing build folder..."
        sudo ninja -C build install &>/dev/null
        echo "Done"
	echo "Update complete"

elif [ "$d" == "Uninstall" ]; then
        echo '  _____ _             _           _'
        echo ' /  ___| |           | |         | |'
        echo ' \ `--.| |_ __ _ _ __| |     __ _| |__  ___'
        echo '  `--. \ __/ _` | '"'"'__| |    / _` | '"'"'_ \/ __|'
        echo ' /\__/ / || (_| | |  | |___| (_| | |_) \__ \'
        echo ' \____/ \__\__,_|_|  \_____/\__,_|_.__/|___/'
        echo
        echo '************** Star Labs Theme *************'
        echo
        echo "Uninstalling..."

        echo -ne "Uninstalling GDM theme..."
	sudo update-alternatives --remove gdm3.css /usr/share/gnome-shell/theme/StarLabs/gnome-shell.css
        echo "Done"

        echo -ne "Compiling schemas..."
        sudo glib-compile-schemas /usr/share/glib-2.0/schemas
        echo "Done"

        echo -ne "Uninstalling Plymouth theme..."
        sudo update-alternatives --remove default.plymouth /usr/share/plymouth/themes/StarLabs/StarLabs.plymouth
        sudo update-initramfs -u
        echo "Done"

        echo -ne "Updating grub..."
        sudo update-grub
        echo "Done"

        echo -ne "Uninstalling current version..."
        sudo ninja -C build uninstall &>/dev/null
        echo "Done"
	echo "Uninstallation complete"
fi
