#!/bin/sh

set -e

if [ "$1" = configure ]; then
	update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/StarLabs/StarLabs.plymouth 150 --slave /usr/share/plymouth/themes/StarLabs/StarLabs-Firmware.plymouth
	update-initramfs -u
fi



