usr/share/gnome-shell/modes/starlabs-orange.json
usr/share/xsessions/StarLabs-Orange.desktop
usr/share/wayland-sessions/StarLabs-Orange-wayland.desktop
usr/share/glib-2.0/schemas/99_StarLabs-Orange.gschema.override
usr/share/gnome-shell/modes/starlabs-orange-dark.json
usr/share/xsessions/StarLabs-Orange-Dark.desktop
usr/share/wayland-sessions/StarLabs-Orange-Dark-wayland.desktop
usr/share/glib-2.0/schemas/99_StarLabs-Orange-Dark.gschema.override
