#!/bin/sh

#	set -e

#	if [ "$1" = remove ]; then
#		gtk-update-icon-cache -qtf /usr/share/icons
#	fi

# Automatically added by dh_icons/12ubuntu1
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/StarLabs
fi
# End automatically added section


