#!/bin/sh

set -e

if [ "$1" = configure ]; then
	gtk-update-icon-cache -qtf /usr/share/icons/StarLabs
fi

# Automatically added by dh_icons/11.3.2ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/StarLabs
	fi
fi
# End automatically added section


