#!/bin/sh

set -e

if [ "$1" = remove ]; then
	gtk-update-icon-cache -qtf /usr/share/icons
fi

# Automatically added by dh_icons/11.3.2ubuntu1
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/StarLabs
fi
# End automatically added section


